version: "3.9"

services:
  database:
    image: postgres
    container_name: database_infosistemas
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_DB=infosistemas
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: infosistemas
    restart: always
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database



volumes:
  pgdata:
    driver: local